apiVersion: v1
kind: Secret
metadata:
  name: otus-work-3-app-secrets
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOmRpbTRob21lQG90dXMtd29yay0zLWRiLXNlcnZpY2U6MTU0MzIvb3R1c19kYg==
  POSTGRES_DB: b3R1c19kYg==
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: ZGltNGhvbWU=