apiVersion: batch/v1
kind: Job
metadata:
  name: otus-work-3-app-migration-job
spec:
  template:
    spec:
      containers:
      - name: otis-work3
        image: legioner4/otis-work:3.0
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: otus-work-3-app-secrets
              key: DATABASE_URL
        command: ["/opt/project/scripts/migrate.sh"]
      restartPolicy: Never