apiVersion: v1
kind: Secret
metadata:
  name: otus-work-3-app-secrets
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOmRpbTRob21lQG90dXMtcG9zdGdyZXNxbC1obDo1NDMyL290dXNfZGI=
  POSTGRES_DB: b3R1c19kYg==
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: ZGltNGhvbWU=