apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-work-3-db-deployment
  labels:
    app: otus-work-3-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otus-work-3-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: otus-work-3-db
    spec:
      containers:
      - name: postgres
        image: postgres:11
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: otus-work-3-app-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: otus-work-3-app-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: otus-work-3-app-secrets
              key: POSTGRES_PASSWORD